services:            
    idempotency.response_listener:
        class: Conejerock\IdempotencyBundle\EventListener\ResponseListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onIdempotentResponse, priority: 100  }
        arguments:
            $container: '@service_container'
                
    idempotency.controller_listener:
        class: Conejerock\IdempotencyBundle\EventListener\ControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onIdempotentController, priority: 100  }
        arguments:
            $container: '@service_container'
            
    idempotency.extractor.body:
        class: Conejerock\IdempotencyBundle\Extractor\BodyExtractor

    idempotency.extractor.headers:
        class: Conejerock\IdempotencyBundle\Extractor\HeadersExtractor   
            
    idempotency.extractor.query:
        class: Conejerock\IdempotencyBundle\Extractor\QueryExtractor               
