services:            
    idempotency.response_listener:
        class: Conejerock\IdempotencyBundle\EventListener\ResponseListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onIdempotentResponse, priority: 100  }
        arguments:
            $cacheInterface: '@cache.app'    
                
    idempotency.controller_listener:
        class: Conejerock\IdempotencyBundle\EventListener\ControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onIdempotentController, priority: 100  }
        arguments:
            $cacheInterface: '@cache.app'
